const customers=[
{name:"Sarah Johnson",dog:"Max",breed:"Golden Retriever",age:4,address:"123 Main Street",phone:"(713) 555-0142",instructions:"Key is under the flowerpot. Max gets nervous around large dogs. Give him water when you return. Lock the back door.",emoji:"🐕"},
{name:"Mike Smith",dog:"Bella",breed:"Labrador Mix",age:2,address:"456 Oak Drive",phone:"(713) 555-0198",instructions:"Bella loves the park. Please avoid the construction area.",emoji:"🐶"},
{name:"Jessica Williams",dog:"Charlie",breed:"Cavalier King Charles",age:6,address:"789 Pine Street",phone:"(832) 555-0121",instructions:"Charlie can be shy at first. Bring him back inside through the side door.",emoji:"🐩"}
];
const walks=[{time:"9:00 AM",dur:"30 min",i:0},{time:"11:30 AM",dur:"45 min",i:1},{time:"2:00 PM",dur:"30 min",i:2}];
let page="home",selected=0,seconds=0,timer=null;
const app=document.getElementById("app"), nav=document.getElementById("nav");
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1600)}
function go(p){page=p;render()}
function card(w){let c=customers[w.i];return `<div class="card" onclick="selected=${w.i};go('details')"><div class="walk"><div class="dog">${c.emoji}</div><div class="grow"><h3>${c.dog}</h3><div>${c.name}</div><div class="meta">${w.time} • ${w.dur}</div></div><span class="badge">Scheduled</span></div><div class="meta" style="margin-left:64px">📍 ${c.address}</div></div>`}
function navBar(){return `<button class="${page==='home'?'active':''}" onclick="go('home')"><span>⌂</span>Today</button><button class="${page==='calendar'?'active':''}" onclick="go('calendar')"><span>▣</span>Calendar</button><button class="${page==='customers'?'active':''}" onclick="go('customers')"><span>♙</span>Customers</button><button onclick="go('schedule')"><span>＋</span>Schedule</button>`}
function home(){return `<div class="content"><div class="top"><div><h1>Good morning! 🐾</h1><div class="muted">Wednesday, August 19</div></div><div class="avatar">🐾</div></div><div class="hero"><div class="muted">TODAY'S WALKS</div><div class="heroNum">3 walks</div></div><div class="row"><h2>Today's Walks</h2><button class="btn small" onclick="go('schedule')">+ Schedule</button></div>${walks.map(card).join("")}</div>`}
function details(){let c=customers[selected],w=walks.find(x=>x.i===selected);return `<div class="content"><button class="back" onclick="go('home')">‹ Back</button><div class="center"><div class="bigdog">${c.emoji}</div><h1>${c.dog}</h1><div class="muted">${c.name}</div></div><div class="card"><div class="row"><div><b>${w.time}</b><div class="meta">${w.dur} walk</div></div><span class="badge">Today</span></div></div><div class="card"><h3>📍 Address</h3><div>${c.address}</div><button class="btn secondary" style="margin-top:10px" onclick="toast('Maps would open here')">Get Directions</button></div><div class="card"><h3>⚠️ Important Instructions</h3><p class="meta" style="line-height:1.6;color:#18231e">${c.instructions}</p></div><div class="card"><h3>🐾 Dog Information</h3><div class="row"><span>Breed</span><b>${c.breed}</b></div><div class="row" style="margin-top:8px"><span>Age</span><b>${c.age}</b></div></div><button class="btn" onclick="startWalk()">START WALK</button></div>`}
function walk(){let c=customers[selected];return `<div class="content"><button class="back" onclick="go('details')">‹ Walk Details</button><div class="center"><div class="bigdog">${c.emoji}</div><h1>${c.dog}'s Walk</h1><div class="muted">Walk in progress</div><div class="timer" id="timer">00:00</div><div class="card"><div class="row"><span>Customer</span><b>${c.name}</b></div><div class="row" style="margin-top:10px"><span>Address</span><b>${c.address}</b></div></div><button class="btn orange" onclick="endWalk()">END WALK</button></div></div>`}
function recap(){let c=customers[selected];return `<div class="content"><button class="back" onclick="go('details')">‹ Back</button><div class="center"><div class="bigdog">🎉</div><h1>Walk Complete!</h1><div class="muted">${c.dog} • 32 minutes</div></div><div class="card"><h3>How did it go?</h3><div class="actions"><button class="btn secondary" onclick="toast('Marked Great!')">😊 Great</button><button class="btn secondary" onclick="toast('Marked Okay')">😐 Okay</button><button class="btn secondary" onclick="toast('Issue noted')">⚠️ Issue</button></div></div><div class="label">WALK RECAP</div><textarea id="note">${c.dog} had a great walk today! We walked around the neighborhood and he went potty twice. He was happy and energetic when we got back.</textarea><div class="label">PHOTOS</div><div class="photo" onclick="toast('Photo picker would open here')">📷 Add Photos</div><button class="btn" onclick="toast('Walk recap sent!');setTimeout(()=>go('home'),900)">SEND WALK RECAP</button></div>`}
function customersPage(){return `<div class="content"><div class="top"><div><h1>Customers</h1><div class="muted">${customers.length} active customers</div></div><button class="btn small" onclick="go('add')">+ Add</button></div><input class="input" placeholder="🔎 Search customers" oninput="filterCustomers(this.value)"><div id="customerList">${customers.map((c,i)=>customerCard(c,i)).join("")}</div></div>`}
function customerCard(c,i){return `<div class="card" onclick="selected=${i};go('profile')"><div class="walk"><div class="dog">${c.emoji}</div><div class="grow"><h3>${c.name}</h3><div>${c.dog}</div><div class="meta">${c.breed}</div></div><span style="color:#2f7d5b;font-size:22px">›</span></div></div>`}
function filterCustomers(q){document.getElementById("customerList").innerHTML=customers.filter(c=>(c.name+c.dog+c.breed).toLowerCase().includes(q.toLowerCase())).map(c=>customerCard(c,customers.indexOf(c))).join("")}
function profile(){let c=customers[selected];return `<div class="content"><button class="back" onclick="go('customers')">‹ Back</button><div class="center"><div class="bigdog">${c.emoji}</div><h1>${c.name}</h1><div class="muted">Customer profile</div></div><div class="card"><h3>🐕 ${c.dog}</h3><div class="meta">${c.breed} • ${c.age}</div></div><div class="card"><h3>Contact</h3><p>📱 ${c.phone}</p><p>📍 ${c.address}</p></div><div class="card"><h3>Special Instructions</h3><p class="meta" style="line-height:1.6;color:#18231e">${c.instructions}</p></div><button class="btn" onclick="go('schedule')">SCHEDULE A WALK</button></div>`}
function schedule(){return `<div class="content"><button class="back" onclick="go('home')">‹ Back</button><h1>Schedule Walk</h1><div class="muted">Create a new appointment</div><div class="label">CUSTOMER & DOG</div><select class="input">${customers.map((c,i)=>`<option>${c.name} — ${c.dog}</option>`).join("")}</select><div class="label">DATE</div><input class="input" type="date" value="2026-08-21"><div class="label">TIME</div><select class="input"><option>9:00 AM</option><option>10:30 AM</option><option>11:30 AM</option><option>2:00 PM</option><option>4:00 PM</option></select><div class="label">DURATION</div><select class="input"><option>30 minutes</option><option>45 minutes</option><option>60 minutes</option></select><button class="btn" onclick="toast('Walk scheduled!');setTimeout(()=>go('home'),800)">CONFIRM WALK</button></div>`}
function add(){return `<div class="content"><button class="back" onclick="go('customers')">‹ Back</button><h1>New Customer</h1><div class="muted">Add a customer and their dog</div>${["Customer name","Phone","Email","Address","Dog name","Breed"].map(x=>`<div class="label">${x.toUpperCase()}</div><input class="input" placeholder="${x}">`).join("")}<div class="label">SPECIAL INSTRUCTIONS</div><textarea placeholder="Keys, doors, behavior, feeding, etc."></textarea><button class="btn" onclick="toast('Customer saved!');setTimeout(()=>go('customers'),800)">SAVE CUSTOMER</button></div>`}
function calendar(){return `<div class="content"><div class="top"><div><h1>Calendar</h1><div class="muted">August 2026</div></div><button class="btn small" onclick="go('schedule')">+ Walk</button></div><div class="card"><div class="cal">${['S','M','T','W','T','F','S',26,27,28,29,30,31,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31].map((x,i)=>`<div class="${x===19?'sel':''}">${x}</div>`).join("")}</div></div><h2>August 19</h2>${walks.map(card).join("")}</div>`}
function render(){let v={home,details,walk,recap,customers:customersPage,profile,schedule,add,calendar}[page]||home;app.innerHTML=v();nav.innerHTML=["home","calendar","customers","schedule"].includes(page)?navBar():"";if(page==="walk"&&timer)updateTimer()}
function startWalk(){seconds=0;page="walk";timer=setInterval(()=>{seconds++;updateTimer()},1000);render()}
function updateTimer(){let e=document.getElementById("timer");if(e)e.textContent=String(Math.floor(seconds/60)).padStart(2,"0")+":"+String(seconds%60).padStart(2,"0")}
function endWalk(){clearInterval(timer);timer=null;page="recap";render()}
render();
